name: Release
on:
  release:
    types: [published]
  workflow_dispatch:


jobs:
  tag:
    name: Add/update 'latest' tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run latest-tag
        uses: EndBug/latest-tag@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    name: Publish on NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9

      - name: Install Node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Package
        run: pnpm run build

      - name: Publish Package
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    name: Publish on GPR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9

      - name: Install Node v18 for GPR
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@snazzah'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Package
        run: pnpm run build && pnpm run gpr

      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
