name: Tests
on:
  push:
    branches:
      - "*"
      - "!gh-pages"
    paths:
      - "src/**"
      - "test/**"
      - "package.json"
      - ".github/workflows/test.yml"
      - "pnpm-lock.yaml"
  pull_request:
    branches:
      - "*"
      - "!docs"
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9

      - name: Install Node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Tests
        run: pnpm run test
